CREATE UNIQUE INDEX "users_supabaseId_key" ON "users"("supabaseId");
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE INDEX "users_email_idx" ON "users"("email");
CREATE INDEX "users_subscriptionPlan_subscriptionStatus_idx" ON "users"("subscriptionPlan", "subscriptionStatus");
CREATE UNIQUE INDEX "subscriptions_userId_key" ON "subscriptions"("userId");
CREATE UNIQUE INDEX "subscriptions_stripeCustomerId_key" ON "subscriptions"("stripeCustomerId");
CREATE UNIQUE INDEX "subscriptions_stripeSubscriptionId_key" ON "subscriptions"("stripeSubscriptionId");
CREATE INDEX "trends_category_status_idx" ON "trends"("category", "status");
CREATE INDEX "trends_signalStrength_idx" ON "trends"("signalStrength" DESC);
CREATE INDEX "trends_source_geographicFocus_idx" ON "trends"("source", "geographicFocus");
CREATE INDEX "trends_detectedAt_idx" ON "trends"("detectedAt" DESC);
CREATE UNIQUE INDEX "trends_titleEn_key" ON "trends"("titleEn");
CREATE INDEX "trend_content_trendId_platform_idx" ON "trend_content"("trendId", "platform");
CREATE INDEX "trend_content_contentType_generatedBy_idx" ON "trend_content"("contentType", "generatedBy");
CREATE INDEX "user_trends_userId_isSaved_idx" ON "user_trends"("userId", "isSaved");
CREATE INDEX "user_trends_userId_relevanceScore_idx" ON "user_trends"("userId", "relevanceScore" DESC);
CREATE UNIQUE INDEX "user_trends_userId_trendId_key" ON "user_trends"("userId", "trendId");
CREATE INDEX "alerts_userId_isRead_idx" ON "alerts"("userId", "isRead");
CREATE INDEX "alerts_userId_createdAt_idx" ON "alerts"("userId", "createdAt" DESC);
CREATE UNIQUE INDEX "alert_settings_userId_alertType_key" ON "alert_settings"("userId", "alertType");
CREATE INDEX "influencers_platform_followersCount_idx" ON "influencers"("platform", "followersCount" DESC);
CREATE INDEX "influencers_engagementRate_idx" ON "influencers"("engagementRate" DESC);
CREATE UNIQUE INDEX "influencers_handle_platform_key" ON "influencers"("handle", "platform");
CREATE INDEX "influencer_matches_trendId_matchScore_idx" ON "influencer_matches"("trendId", "matchScore" DESC);
CREATE UNIQUE INDEX "influencer_matches_trendId_influencerId_key" ON "influencer_matches"("trendId", "influencerId");
CREATE INDEX "trend_history_trendId_recordedAt_idx" ON "trend_history"("trendId", "recordedAt" DESC);
CREATE INDEX "collector_runs_source_startedAt_idx" ON "collector_runs"("source", "startedAt" DESC);

ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trend_content" ADD CONSTRAINT "trend_content_trendId_fkey" FOREIGN KEY ("trendId") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_trends" ADD CONSTRAINT "user_trends_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_trends" ADD CONSTRAINT "user_trends_trendId_fkey" FOREIGN KEY ("trendId") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "alerts" ADD CONSTRAINT "alerts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "alerts" ADD CONSTRAINT "alerts_trendId_fkey" FOREIGN KEY ("trendId") REFERENCES "trends"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "alert_settings" ADD CONSTRAINT "alert_settings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "influencer_matches" ADD CONSTRAINT "influencer_matches_trendId_fkey" FOREIGN KEY ("trendId") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "influencer_matches" ADD CONSTRAINT "influencer_matches_influencerId_fkey" FOREIGN KEY ("influencerId") REFERENCES "influencers"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "trend_history" ADD CONSTRAINT "trend_history_trendId_fkey" FOREIGN KEY ("trendId") REFERENCES "trends"("id") ON DELETE CASCADE ON UPDATE CASCADE;
