import type { TrendItem } from "@/types";

export const MOCK_TRENDS: TrendItem[] = [
  {
    id: "1",
    nameAr: "عباءة الفراشة",
    nameEn: "Butterfly Abaya",
    descriptionAr: "تصميم عباءة فريد بأكمام على شكل فراشة يجتاح السوق الخليجي",
    category: "FASHION",
    status: "RISING",
    score: 94,
    momentum: 0.82,
    searchVolume: 45000,
    socialMentions: 12400,
    tags: ["عباءة", "موضة", "خليجي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    nameAr: "سماعات الهواء المفتوح",
    nameEn: "Open-Ear Headphones",
    descriptionAr: "سماعات لاسلكية بتصميم مفتوح تتيح سماع المحيط مع الموسيقى",
    category: "ELECTRONICS",
    status: "PEAK",
    score: 88,
    momentum: 0.45,
    searchVolume: 38000,
    socialMentions: 9800,
    tags: ["سماعات", "تقنية", "لاسلكي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    nameAr: "طقم المطبخ الياباني",
    nameEn: "Japanese Kitchen Set",
    descriptionAr: "أدوات مطبخ بالتصميم الياباني الأنيق تحقق مبيعات قياسية",
    category: "HOME_DECOR",
    status: "RISING",
    score: 79,
    momentum: 0.68,
    searchVolume: 22000,
    socialMentions: 6500,
    tags: ["مطبخ", "ياباني", "ديكور"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 10800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    nameAr: "كريم السنبلة SPF 50",
    nameEn: "Wheat Germ SPF50 Cream",
    descriptionAr: "كريم حماية من الشمس بزيت جنين القمح ينتشر بسرعة كبيرة",
    category: "BEAUTY",
    status: "RISING",
    score: 85,
    momentum: 0.74,
    searchVolume: 31000,
    socialMentions: 8900,
    tags: ["سكن كير", "حماية شمس", "بيوتي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 5400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    nameAr: "حذاء الترامبولين",
    nameEn: "Bouncy Sole Sneakers",
    descriptionAr: "أحذية رياضية بنعل مرن يشبه الترامبولين يجتاح منصات التواصل",
    category: "FITNESS",
    status: "RISING",
    score: 91,
    momentum: 0.89,
    searchVolume: 52000,
    socialMentions: 18700,
    tags: ["رياضة", "أحذية", "ترند"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    nameAr: "ألعاب تنمية الذكاء",
    nameEn: "Montessori Learning Toys",
    descriptionAr: "ألعاب مونتيسوري لتنمية مهارات الأطفال من 2-8 سنوات",
    category: "KIDS",
    status: "STABLE",
    score: 72,
    momentum: 0.31,
    searchVolume: 18000,
    socialMentions: 4200,
    tags: ["أطفال", "تعليم", "مونتيسوري"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
