import type { TrendItem, InfluencerItem } from "@/types";

export const MOCK_TRENDS: TrendItem[] = [
  {
    id: "1",
    nameAr: "عباءة الفراشة",
    nameEn: "Butterfly Abaya",
    descriptionAr: "تصميم عباءة فريد بأكمام على شكل فراشة يجتاح السوق الخليجي",
    category: "FASHION",
    status: "RISING",
    score: 94,
    momentum: 0.82,
    searchVolume: 45000,
    socialMentions: 12400,
    tags: ["عباءة", "موضة", "خليجي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    nameAr: "سماعات الهواء المفتوح",
    nameEn: "Open-Ear Headphones",
    descriptionAr: "سماعات لاسلكية بتصميم مفتوح تتيح سماع المحيط مع الموسيقى",
    category: "ELECTRONICS",
    status: "PEAK",
    score: 88,
    momentum: 0.45,
    searchVolume: 38000,
    socialMentions: 9800,
    tags: ["سماعات", "تقنية", "لاسلكي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    nameAr: "طقم المطبخ الياباني",
    nameEn: "Japanese Kitchen Set",
    descriptionAr: "أدوات مطبخ بالتصميم الياباني الأنيق تحقق مبيعات قياسية",
    category: "HOME_DECOR",
    status: "RISING",
    score: 79,
    momentum: 0.68,
    searchVolume: 22000,
    socialMentions: 6500,
    tags: ["مطبخ", "ياباني", "ديكور"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 10800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    nameAr: "كريم السنبلة SPF 50",
    nameEn: "Wheat Germ SPF50 Cream",
    descriptionAr: "كريم حماية من الشمس بزيت جنين القمح ينتشر بسرعة كبيرة",
    category: "BEAUTY",
    status: "RISING",
    score: 85,
    momentum: 0.74,
    searchVolume: 31000,
    socialMentions: 8900,
    tags: ["سكن كير", "حماية شمس", "بيوتي"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 5400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    nameAr: "حذاء الترامبولين",
    nameEn: "Bouncy Sole Sneakers",
    descriptionAr: "أحذية رياضية بنعل مرن يشبه الترامبولين يجتاح منصات التواصل",
    category: "FITNESS",
    status: "RISING",
    score: 91,
    momentum: 0.89,
    searchVolume: 52000,
    socialMentions: 18700,
    tags: ["رياضة", "أحذية", "ترند"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    nameAr: "ألعاب تنمية الذكاء",
    nameEn: "Montessori Learning Toys",
    descriptionAr: "ألعاب مونتيسوري لتنمية مهارات الأطفال من 2-8 سنوات",
    category: "KIDS",
    status: "STABLE",
    score: 72,
    momentum: 0.31,
    searchVolume: 18000,
    socialMentions: 4200,
    tags: ["أطفال", "تعليم", "مونتيسوري"],
    sourceUrls: [],
    relatedProducts: [],
    detectedAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_INFLUENCERS: InfluencerItem[] = [
  {
    id: "inf-1",
    name: "نورة المطيري",
    handle: "@noura_style",
    platform: "INSTAGRAM",
    followersCount: 820000,
    engagementRate: 4.8,
    categories: ["FASHION", "BEAUTY"],
    bio: "مدوّنة أزياء سعودية | كل يوم لوك جديد 🌸",
    contactEmail: "noura@influencer.sa",
    priceRange: "3,000 – 8,000 ر.س",
    currency: "SAR",
    isVerified: true,
    isActive: true,
    country: "SA",
    city: "الرياض",
    avgLikes: 39360,
    avgComments: 1420,
    avatarUrl: null,
    profileUrl: "https://instagram.com/noura_style",
    matchedTrendIds: ["1", "4"],
    matchScore: 96,
    matchReasonAr: "جمهورها 78% نساء 18-34 في السعودية ومحتواها يركز على الموضة والعناية",
  },
  {
    id: "inf-2",
    name: "عبدالله التقني",
    handle: "@tech_abdallah",
    platform: "TIKTOK",
    followersCount: 1450000,
    engagementRate: 6.2,
    categories: ["ELECTRONICS", "GAMING"],
    bio: "مراجعات تقنية بالعربي 🎮📱",
    contactEmail: "tech@abdallah.ae",
    priceRange: "5,000 – 15,000 ر.س",
    currency: "SAR",
    isVerified: true,
    isActive: true,
    country: "AE",
    city: "دبي",
    avgLikes: 89900,
    avgComments: 3100,
    avatarUrl: null,
    profileUrl: "https://tiktok.com/@tech_abdallah",
    matchedTrendIds: ["2"],
    matchScore: 91,
    matchReasonAr: "متخصص في الإلكترونيات بجمهور 65% شباب 18-28 في الخليج",
  },
  {
    id: "inf-3",
    name: "ريم الديكور",
    handle: "@reem_deco",
    platform: "SNAPCHAT",
    followersCount: 390000,
    engagementRate: 5.5,
    categories: ["HOME_DECOR", "FOOD"],
    bio: "ديكور بيتك بأسلوبك 🏠✨",
    contactEmail: "reem@deco.sa",
    priceRange: "1,500 – 4,000 ر.س",
    currency: "SAR",
    isVerified: false,
    isActive: true,
    country: "SA",
    city: "جدة",
    avgLikes: 21450,
    avgComments: 870,
    avatarUrl: null,
    profileUrl: "https://snapchat.com/add/reem_deco",
    matchedTrendIds: ["3"],
    matchScore: 88,
    matchReasonAr: "محتواها يغطي ديكور المنزل والمطبخ بجمهور خليجي نسائي بشكل رئيسي",
  },
  {
    id: "inf-4",
    name: "سارة الرياضة",
    handle: "@sara_fit_kw",
    platform: "INSTAGRAM",
    followersCount: 215000,
    engagementRate: 7.1,
    categories: ["FITNESS", "FASHION"],
    bio: "كوتش لياقة معتمدة | الصحة أولاً 💪",
    contactEmail: "sara@fitkw.com",
    priceRange: "800 – 2,500 ر.س",
    currency: "SAR",
    isVerified: false,
    isActive: true,
    country: "KW",
    city: "الكويت",
    avgLikes: 15265,
    avgComments: 610,
    avatarUrl: null,
    profileUrl: "https://instagram.com/sara_fit_kw",
    matchedTrendIds: ["5"],
    matchScore: 93,
    matchReasonAr: "متخصصة في اللياقة والأحذية الرياضية بتفاعل مرتفع جداً",
  },
  {
    id: "inf-5",
    name: "أم فهد التعليمية",
    handle: "@umfahad_kids",
    platform: "TIKTOK",
    followersCount: 540000,
    engagementRate: 8.3,
    categories: ["KIDS", "FOOD"],
    bio: "أنشطة وألعاب للأطفال 🧸 | أم لثلاثة",
    contactEmail: "umfahad@kids.sa",
    priceRange: "2,000 – 5,500 ر.س",
    currency: "SAR",
    isVerified: true,
    isActive: true,
    country: "SA",
    city: "الدمام",
    avgLikes: 44820,
    avgComments: 2100,
    avatarUrl: null,
    profileUrl: "https://tiktok.com/@umfahad_kids",
    matchedTrendIds: ["6"],
    matchScore: 87,
    matchReasonAr: "جمهورها أمهات خليجيات واهتمامها الرئيسي تطوير الأطفال والألعاب التعليمية",
  },
  {
    id: "inf-6",
    name: "خالد المطبخ",
    handle: "@khaled_kitchen",
    platform: "YOUTUBE",
    followersCount: 980000,
    engagementRate: 3.9,
    categories: ["FOOD", "HOME_DECOR"],
    bio: "وصفات خليجية أصيلة 🍖 | يوتيوب أسبوعياً",
    contactEmail: "khaled@kitchen.ae",
    priceRange: "4,000 – 12,000 ر.س",
    currency: "SAR",
    isVerified: true,
    isActive: true,
    country: "AE",
    city: "أبوظبي",
    avgLikes: 38220,
    avgComments: 1540,
    avatarUrl: null,
    profileUrl: "https://youtube.com/@khaled_kitchen",
    matchedTrendIds: ["3"],
    matchScore: 82,
    matchReasonAr: "يغطي الطبخ وأدوات المطبخ بجمهور عربي واسع على يوتيوب",
  },
];
